#!/bin/sh

#export PATH="/home/ajender/QemuV1/buildroot-2023.02.4/output/host/bin:${PATH}"
compiler_path=/home/ajender/buildroot-2023.02.4/output/host/bin
rm /home/ajender/Hello/hello
$compiler_path/arm-buildroot-linux-gnueabi-gcc-11.4.0  /home/ajender/Hello/hello.c -o /home/ajender/Hello/hello

mount -t ext2 -o rw,loop /home/ajender/buildroot-2023.02.4/output/images/rootfs.ext2 /home/ajender/try/
cp /home/ajender/Hello/hello /home/ajender/try/root/
umount /home/ajender/try/